# Generated by Django 5.1.7 on 2025-04-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='autor',
            new_name='nome',
        ),
    ]
