# Generated by Django 5.2 on 2025-04-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_autor_autor_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
